name: 21f1002821@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '30 6 * * *' # Runs daily at 06:30 UTC

  workflow_dispatch: # Allows manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File (Step for 21f1002821@ds.study.iitm.ac.in)
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "21f1002821@ds.study.iitm.ac.in"
          git add last_run.txt
          git commit -m "Automated daily commit: $(date)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/kushabarodekar/github-action-demo.git HEAD:main
