name: 21f1002821@ds.study.iitm.ac.in

on:
  schedule:
    # Runs every day at 06:30 UTC (Adjust as needed)
    - cron: '30 6 * * *'

  workflow_dispatch: # Allows manual trigger

jobs:
  daily-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File (Step for kushabarodekar@gmail.com)
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "kushabarodekar@gmail.com"
          git add last_run.txt
          git commit -m "Automated daily commit: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
